import type {
  EventRecord,
  Product,
  Metrics,
  Feedback,
} from "@cocacola-ei/contracts";
export const demoEventId = "b21b5000-a481-4cb9-8b41-100000000001";
export const products: Product[] = [
  {
    id: "zero",
    sku: "CCZ-350",
    name: "Coca-Cola Zero Azúcar 350 ml",
    brandLine: "Coca-Cola Zero",
    isActive: true,
  },
  {
    id: "original",
    sku: "CCO-350",
    name: "Coca-Cola Original 350 ml",
    brandLine: "Coca-Cola",
    isActive: true,
  },
  {
    id: "sprite",
    sku: "SPR-350",
    name: "Sprite 350 ml",
    brandLine: "Sprite",
    isActive: true,
  },
  {
    id: "vanilla",
    sku: "CCV-350",
    name: "Coca-Cola Zero Vainilla 350 ml",
    brandLine: "Coca-Cola Creations",
    isActive: true,
  },
];
export const events: EventRecord[] = [
  {
    id: demoEventId,
    name: "Lollapalooza Coca-Cola Stage",
    publicCode: "LOLLA26",
    type: "FESTIVAL",
    status: "ACTIVE",
    startsAt: "2026-10-02T18:00:00Z",
    endsAt: "2026-10-03T02:00:00Z",
    timezone: "America/Santiago",
    location: "Parque Cerrillos",
    city: "Santiago",
    capacity: 5000,
    attendanceGoal: 4000,
    activities: [
      {
        id: "stand-zero",
        name: "Stand Zero",
        category: "SAMPLING",
        maxClaimsPerUser: 1,
        isActive: true,
        productIds: ["zero", "original"],
      },
      {
        id: "stand-sprite",
        name: "Zona Sprite",
        category: "SAMPLING",
        maxClaimsPerUser: 1,
        isActive: true,
        productIds: ["sprite"],
      },
      {
        id: "photo",
        name: "Photocall",
        category: "PHOTO_BOOTH",
        maxClaimsPerUser: 1,
        isActive: true,
        productIds: [],
      },
    ],
    staff: [
      {
        id: "demo-staff",
        label: "Acceso principal",
        canCheckIn: true,
        allowedActivityIds: ["stand-zero", "photo"],
        revokedAt: null,
      },
    ],
    campaign: {
      codePrefix: "LOLLA26",
      discountLabel: "30% en tu próximo pack Coca-Cola Zero",
      policy: "MIN_SENTIMENT",
      minSentiment: 3,
      expiresAt: "2026-11-02T23:59:00Z",
    },
  },
  {
    id: "b21b5000-a481-4cb9-8b41-100000000002",
    name: "Coca-Cola Zero Vainilla",
    publicCode: "ZEROVAN26",
    type: "PRODUCT_LAUNCH",
    status: "PUBLISHED",
    startsAt: "2026-10-16T18:00:00Z",
    endsAt: "2026-10-16T23:00:00Z",
    timezone: "America/Santiago",
    location: "Parque Bicentenario",
    city: "Santiago",
    capacity: 1200,
    attendanceGoal: 1000,
    activities: [
      {
        id: "vanilla-stand",
        name: "Descubre Vainilla",
        category: "SAMPLING",
        maxClaimsPerUser: 1,
        isActive: true,
        productIds: ["vanilla"],
      },
    ],
    staff: [],
    campaign: null,
  },
  {
    id: "b21b5000-a481-4cb9-8b41-100000000003",
    name: "Fan Fest Copa Mundial",
    publicCode: "FANFEST26",
    type: "SPORTS",
    status: "COMPLETED",
    startsAt: "2026-07-19T16:00:00Z",
    endsAt: "2026-07-19T23:00:00Z",
    timezone: "America/Santiago",
    location: "Parque O’Higgins",
    city: "Santiago",
    capacity: 3500,
    attendanceGoal: 3000,
    activities: [],
    staff: [],
    campaign: null,
  },
];
export const metrics: Record<string, Metrics> = {
  [demoEventId]: {
    registered: 4210,
    attended: 3120,
    attendanceGoal: 4000,
    recurrentAttendees: 640,
    engagedAttendees: 2780,
    blockedFraudAttempts: 57,
    claimsByProduct: [
      { productId: "zero", name: products[0].name, claims: 1830 },
      { productId: "original", name: products[1].name, claims: 940 },
      { productId: "sprite", name: products[2].name, claims: 510 },
    ],
    feedback: {
      requested: 2900,
      completed: 610,
      avgSentiment: 4.21,
      purchaseIntentRate: 63.4,
    },
    couponsIssued: 540,
    updatedAt: "2026-10-02T23:45:00Z",
  },
  [events[2].id]: {
    registered: 3400,
    attended: 2870,
    attendanceGoal: 3000,
    recurrentAttendees: 430,
    engagedAttendees: 2450,
    blockedFraudAttempts: 23,
    claimsByProduct: [
      { productId: "original", name: products[1].name, claims: 2480 },
    ],
    feedback: {
      requested: 2870,
      completed: 690,
      avgSentiment: 4.5,
      purchaseIntentRate: 71.2,
    },
    couponsIssued: 620,
    updatedAt: "2026-07-20T23:00:00Z",
  },
};
export const feedback: Feedback[] = [
  {
    id: "f1",
    eventId: demoEventId,
    status: "COMPLETED",
    participant: { firstName: "Valentina", city: "Ñuñoa", ageRange: "25–34" },
    inputType: "AUDIO",
    transcription:
      "La Zero de vainilla es súper refrescante, la compraría para compartir con mis amigos. Me encantó la música y la energía del evento.",
    sentimentScore: 5,
    purchaseIntent: true,
    keyTopics: ["sabor", "música"],
    productId: "zero",
    receivedAt: "2026-10-02T23:42:00Z",
  },
  {
    id: "f2",
    eventId: demoEventId,
    status: "COMPLETED",
    participant: { firstName: "Diego", city: "Santiago", ageRange: "18–24" },
    inputType: "AUDIO",
    transcription:
      "Buen ambiente, la bebida bien fría y el equipo muy atento. Volvería a una experiencia como esta.",
    sentimentScore: 4,
    purchaseIntent: false,
    keyTopics: ["temperatura", "staff"],
    productId: "original",
    receivedAt: "2026-10-02T23:39:00Z",
  },
  {
    id: "f3",
    eventId: demoEventId,
    status: "COMPLETED",
    participant: {
      firstName: "Camila",
      city: "Providencia",
      ageRange: "25–34",
    },
    inputType: "TEXT",
    transcription:
      "La fila del stand estaba demasiado larga. Me gustó el sabor, pero tuve que esperar mucho tiempo.",
    sentimentScore: 2,
    purchaseIntent: false,
    keyTopics: ["filas", "organización"],
    productId: "zero",
    receivedAt: "2026-10-02T23:36:00Z",
  },
  {
    id: "f4",
    eventId: demoEventId,
    status: "FAILED",
    participant: { firstName: "Martín", city: "Maipú", ageRange: "35–44" },
    inputType: "AUDIO",
    transcription: null,
    sentimentScore: null,
    purchaseIntent: null,
    keyTopics: [],
    productId: "sprite",
    receivedAt: "2026-10-02T23:30:00Z",
  },
  {
    id: "f5",
    eventId: events[2].id,
    status: "COMPLETED",
    participant: { firstName: "Ana", city: "Santiago", ageRange: "25–34" },
    inputType: "TEXT",
    transcription:
      "Excelente ambiente para ver el partido. La Coca-Cola estaba helada, compraría un pack para el próximo encuentro.",
    sentimentScore: 5,
    purchaseIntent: true,
    keyTopics: ["ambiente", "temperatura"],
    productId: "original",
    receivedAt: "2026-07-19T23:00:00Z",
  },
];
